# ~/.ticker.yaml
show-summary: true
show-tags: true
show-fundamentals: true
show-separator: true
show-holdings: true
interval: 5
currency: USD
currency-summary-only: false
watchlist:
  - BTC-USD
  - ETH-USD
  - ADA-USD
  - XPR-USD
  - SHIB-USD
  - DOGE-USD
  - LTC-USD
  - BCH-USD
  - XMR-USD
